# Generated by Django 5.2.12 on 2026-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_teacher_profile_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedcourse',
            name='fail_grades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='completedcourse',
            name='pass_percentage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
