# Generated by Django 5.2.12 on 2026-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_completedcourse_fail_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedcourse',
            name='passed_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
