# Generated by Django 5.2.12 on 2026-05-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
